Add rds-postgres module
alibabacloud-automation/terraform-alicloud-rds-postgres pull request #1
Opened 2020-02-06 07:37 UTC by Rich-yi

2020-02-06 08:06 UTC, zql-tqy commented on README-CN.md
> +region = var.region
缩进

2020-02-06 08:06 UTC, zql-tqy commented on README-CN.md
> +  account_password     = "yourpassword123"
fmt

2020-02-06 08:06 UTC, zql-tqy commented on README-CN.md
> +* [Postgre SQL 实例完整创建示例创建示例](https://github.com/terraform-alicloud-modules/terraform-alicloud-rds-postgres/tree/master/examples)
创建完整示例

2020-02-06 08:06 UTC, zql-tqy commented on README-CN.md
> +* [database](https://github.com/terraform-alicloud-modules/terraform-alicloud-rds-postgres/tree/master/modules/database)
database 模块 下面一样，把上面的子模块的子去掉吧

2020-02-06 08:06 UTC, zql-tqy commented on example/main.tf
> +  // instance_type               = "ecs.n4.small"
不需要的删掉吧

2020-02-06 08:06 UTC, zql-tqy commented on modules/database/main.tf
> +  version                 = ">=1.64.0"
去掉

2020-02-06 08:06 UTC, zql-tqy commented on modules/postgre_sql/variables.tf
> +  description = "Postgre SQL Instance type, for example: ecs.n4.small. full list is : https://www.alibabacloud.com/help/zh/doc-detail/26312.htm"
这个有type么？

2020-02-06 08:06 UTC, zql-tqy commented on outputs.tf
> +output "this_db_instance_id" {
建议####整个module中用统一长度，上面空一行下面直接挨着写，和你这个写一样应该比较整齐

2020-02-07 14:07 UTC, zql-tqy commented on README-CN.md
> +  alarm_rule_statistics      = "Average"
格式

2020-02-07 14:07 UTC, zql-tqy commented on README-CN.md
> +  # Rds Instance
建议这种注释上面####都空一行吧，下面紧贴着写，长度一致，看着比较整齐

2020-02-07 14:07 UTC, zql-tqy commented on README-CN.md
> +
中文的readme使用中问的标点

2020-02-07 14:07 UTC, zql-tqy commented on example/complete/outputs.tf
> +output "this_alarm_rule_project" {
这种有关键字的建议与上面的空一行，格式统一

2020-02-07 14:07 UTC, zql-tqy commented on README-CN.md
> +terraform-alicloud-rds-postgres
上面咋还空了一行

2020-02-10 06:09 UTC, xiaozhu36 requested changes

2020-02-10 06:09 UTC, xiaozhu36 commented on main.tf
> +      Engine = local.engine
这个tag再加一个EngineVersion 吧

2020-02-10 06:09 UTC, xiaozhu36 commented on modules/database/variables.tf
> +variable "type" {
这里面的名字前也统一加一个account_吧

2020-02-10 06:09 UTC, xiaozhu36 commented on variables.tf
> +variable "db_instance_id" {
这个db_instance_id 是干啥的，为啥不用 existing_instance_id

2020-02-10 06:09 UTC, xiaozhu36 commented on README-CN.md
> +  security_group_ids = ["11.193.54.0/24", "121.43.18.0/24"]
security_group_id 是 sg- 开头的字符串，不是一个个的ip网段，你这个地方写的是 security_ips

2020-02-10 06:09 UTC, xiaozhu36 commented on README-CN.md
> +    "101.37.74.0/24",
这个地方没必要写这么多的ip网段，写两个假的就行：10.0.xx.xx/24, 101.27.xx.xx/24

2020-02-10 06:09 UTC, xiaozhu36 commented on README-CN.md
> +  instance_type               = "ecs.n4.small"
这个地方的instance type为啥用的是ecs实例的

2020-02-10 06:09 UTC, xiaozhu36 commented on example/complete/main.tf
> +  source = "../../modules/postgre_sql-10-basic"
这个地方不要引用具体的一个子module，直接引用主module

2020-02-10 07:33 UTC, xiaozhu36 requested changes

2020-02-10 07:33 UTC, xiaozhu36 commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12 和阿里云 Provider 1.59.0+。
后面的provider的版本改成 1.71.0+ 吧，这周会发布

2020-02-10 07:33 UTC, xiaozhu36 commented on README-CN.md
> +  }
这个tag应该是instance的参数

2020-02-10 07:33 UTC, xiaozhu36 commented on modules/postgre_sql-10-basic/variables.tf
> +variable "postgre_sql_period" {
这个直接写成 period或者instance_charge_period就行，没必要用postgre_sql_period

2020-02-10 07:33 UTC, xiaozhu36 commented on modules/postgre_sql-10-basic/variables.tf
> +  description = "Postgre SQL Instance type, for example: ecs.n4.small. full list is : https://www.alibabacloud.com/help/zh/doc-detail/26312.htm"
这个描述不对吧

2020-02-10 07:33 UTC, xiaozhu36 commented on modules/postgre_sql-10-basic/variables.tf
> +variable "db_instance_id" {
还是的，这个参数是干啥的，没有用的化就去掉

2020-02-14 23:32 UTC, xiaozhu36 requested changes

2020-02-14 23:32 UTC, xiaozhu36 commented on outputs.tf
> +  value       = concat(alicloud_db_instance.this.*.security_ips, [""])[0]
这个本来就是list，不用取第0个

2020-02-14 23:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "RDS Database version. Value options can refer to the latest docs [CreateDBInstance](https://www.alibabacloud.com/help/doc-detail/26228.htm) 'EngineVersion'"
这个地方说清楚，是PostgresSQL database version. Valid values: xxx  特定的engine是可以列举清楚具体的值的。

2020-02-14 23:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "The name of Postgre SQL Instance. A random name prefixed with 'terraform-rds-' will be set if it is empty."
你这个描述跟实际不符啊，这个参数你设置的defualt值是 tf-module-postgres， 不是terraform-rds-xxx啊

2020-02-14 23:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create backup policy."
Whether to create Postgre SQL instance's backup policy

2020-02-14 23:32 UTC, xiaozhu36 commented on variables.tf
> +  description = "Prefix of an Internet connection string. A random name prefixed with 'tf-rds-' will be set if it is empty."
这个参数有 random name么？

2020-02-14 23:32 UTC, xiaozhu36 commented on variables.tf
> +  default     = "ReadOnly"
Postgre SQl的account_privilege我记得只有一个值，而且不是 ReadOnly

2020-02-17 02:24 UTC, Rich-yi commented on variables.tf
> +  description = "Prefix of an Internet connection string. A random name prefixed with 'tf-rds-' will be set if it is empty."
有的

2020-02-17 06:12 UTC, xiaozhu36 approved these changes

2020-02-17 06:12 UTC, merged